### ISSUE TITLE
Snapshots become huge with Eco2 tools installed

### ISSUE THREAD

**Issue by anatoly-savchenkov** [HBDK/Eco2-Tools#13]
Each Full HA Snapshot becomes 1GB bigger if Eco2 tools are installed.

**Comment by HBDK** [comment]
yeah, that's the size of three python containers.
i'm not sure why but i seem to remember not being able to use the alpine image, but if i get some extra time i can try it again.

in the mean time you could just uninstall keytool and scan, i assume you don't add new thermostat every other day.

**Comment by anatoly-savchenkov** [comment]
Thank you, this is exactly what I did

**Comment by HBDK** [comment]
the new image is based on python-slim, this is still a rather large image (40-50mb) but it is significantly better than the old.
