### ISSUE TITLE
Stopped working for some reason

### ISSUE THREAD

**Issue by Draghmar** [HBDK/Eco2-Tools#14]
Hi
Not sure if that's something for your "wrapper" but for some unknown reason etrv2mqtt stopped connecting to Eco2s. I have two devices and I didn't change the layout so it's not like the range changed. Do you know anything about this? Should I head to keton/etrv2mqtt instead?

**Comment by Draghmar** [comment]
It may be something to do with overall issue with BT having issue working: https://github.com/home-assistant/operating-system/issues/1264 , https://github.com/custom-components/ble_monitor/issues/295 , https://github.com/custom-components/ble_monitor/issues/167

**Comment by HBDK** [comment]
hmm, all my thermostats are off right now so i didn't even notice.

i will find time to investigate soon!

**Comment by Draghmar** [comment]
I've manage to get it back online - forgot to mention it here. I had to restart not only HA but the whole machine. Not sure what was the problem though...Feel free to close this if you'd like.
