### ISSUE TITLE
Getting updated etrv2mqtt to include timezone

### ISSUE THREAD

**Issue by Draghmar** [HBDK/Eco2-Tools#19]
Hi. Is there a chance you could make an update for your package that would include [PR](https://github.com/keton/etrv2mqtt/pull/10) that repairs issue with date not having timezone? Keton doesn't seem to support this as this PR lives there for few months already. :(

**Comment by HBDK** [comment]
Not really!

i don't want to get involved in the development, i would gladly build from a fork that was actively maintained, but until we have a trust worthy and suitable candidate i'm not going to do anything.

**Comment by Draghmar** [comment]
OK, I understand. Thanks for explanation.

**Comment by Mikk36** [comment]
@HBDK , [etrv2mqtt ](https://github.com/keton/etrv2mqtt) has been updated to include the timezone, time for an update 🙂
