### ISSUE TITLE
Problem installing any of three addons

### ISSUE THREAD

**Issue by Draghmar** [HBDK/Eco2-Tools#2]
Hi
I'm currently testing Hassio on Pi Zero W and wanted to try adding my Danfoss valves with your wrappers. I added your repo but when trying to install any of three add-ons I'm getting this message:
```
The command '/bin/sh -c pip3 install 'git+https://github.com/keton/etrv2mqtt.git'' returned a non-zero code: 139
```

**Comment by HBDK** [comment]
I have only tested it on my nuc, I will check if it works a pi4 but zero w is afiak not a official hassos platform (at the very least not a recommend one) and I don't plan on ensuring this will work on pi zero or zero w.

**Comment by Draghmar** [comment]
It's supported but not recommended. Mostly because of lack in performance.
I don't plan on using Zero W as a main platform. I'm just testing things on it. I don't want to invest in more powerful without knowing if it will do things I like it to do ;)
There's a great chance that this won't work on Pi 4 because it's quite similar platform, only more with power.
Anyway, is there a chance you could let me know at least, what this error could mean?

**Comment by HBDK** [comment]
I will make sure it installed on a Pi4 and close this when it does, the error is most likely because the image lacks the tools need to build one of the prerequisites, I had a similar error in another project recently, I'll probably look at it some time during this week.

**Comment by Draghmar** [comment]
I tried using Terminal to use that command but it didn't work when used like above. First of all there's no python and pip installed by default (didn't know that). After installing it still didn't want to work through the UI. But when used Terminal like that:
```
pip3 install 'git+https://github.com/keton/etrv2mqtt.git'
```
it did start installing although stopped with error that there's no `make` (yeah, didn't know that too). After installing it, I tried again and it stopped this time because it can't find `glib` even if it's installed. I'm trying to add it to the `PKG_CONFIG_PATH` but I'm not sure where to look for `.pc` file for it, if it isn't at default `pkgconfig` locations.

**Comment by HBDK** [comment]
Are you running this on your zero w with hassos on? If so please don't it is not the way to run stuff on hassos. You run everything in containers.

**Comment by Draghmar** [comment]
Yes, I did try to run this directly because I wanted to see what the actual output is. 
I'm new to this. I took image from [hass.io](https://www.home-assistant.io/hassio/installation/) and installed it on SD card.

**Comment by HBDK** [comment]
Yeah but these doesn't run directly on hassos but in a container.

**Comment by HBDK** [comment]
Hello @Draghmar it installs and runs just fine on my Pi4.

i don't plan on spending time on getting this to work on the pi zero.

if this turns out it won't install on any of the recommended pies then i will look further into this.

it might also be solved by #3 but i think that task is at least a few weeks away.

**Comment by Draghmar** [comment]
OK, I understand. I'll need to get my hands on some Pi4 or Pi3 then to check it out.

**Comment by HBDK** [comment]
Yeah or run it in a virtual machine.

**Comment by Sylvania2** [comment]
Tested with RPI3 (32bit )and RPI4 (64bit HASSIO image). 
RPI3 has better bluetooth coverage, but RPI4 with SSD is a lot snappier.
Will try your plugin with a secondary HASSIO server running on a Zero or RPI3 to extend the coverage.
best regards

Kim Bennedsgaard Olesen
