### ISSUE TITLE
The thermostat functionality

### ISSUE THREAD

**Issue by G-Christ** [HBDK/Eco2-Tools#4]
Hi @HBDK ,

When Hassio starts up, the climate thermostat is off,

![image](https://user-images.githubusercontent.com/47368726/97329426-4ef84380-1877-11eb-8724-1bfbd9f91920.png)
 
you can turn it on, by clicking on the fire icon, but you cannot turn it off again.

![image](https://user-images.githubusercontent.com/47368726/97329471-5c153280-1877-11eb-83e4-d90dc4b11d30.png)
 
When on, it displays target temperature and Heat, no matter whether current temperature is below or above target temperature.

Is there any functionality behind this?

I expect, when off, the Hassio climate thermostat is not functional and displays "off".
When on:
- and the current temperature is below target temperature, the Danfoss valve opens, and the climate thermostat in Hassio displays "Heat"
- When current temperature reaches above target temperature, the Danfoss valve closes and the climate thermostat in Hassio displays "Idle"

But how do you expect this to work?'

Thanks

**Comment by HBDK** [comment]
This is not really a topic for this project, I only package etrv2mqtt to make it convenient to use I don't maintain the actual code. Please address issues regrading the functionality to the etrv2mqtt project.

That said I think the etrvs are simple thermostats with a setpoint and nothing more they won't report what they are doing and you can't control anything but the desired temperature.  

I would think that heat and off are states inherited from the climate area where some device have several modes (heat, cool, blow etc).

Anyways I think it's safe to ignore them and if you can't go ask keton if he can do something about it
