### ISSUE TITLE
Maybe werid question but how I can actually use this?

### ISSUE THREAD

**Issue by Draghmar** [HBDK/Eco2-Tools#5]
Hi.
I've got myself a RPi 4 where every step needed to add Eco2 works as it should. I have tiles with temp and such.
One of the reasons I was trying all of this is because one the thermostats I have sits right where my PC has exhaust which means the measured temp is way off and schedule doesn't work properly. I can't do anything about those two sitting close to each other so I wanted to use other temperature measurement device (Xiaomi Mijia BLE Temperature and Humidity Sensor to be specific) and control Eco2 by its values.
And I wonder how and if that's even possible? From what I see the only thing I can change is setting 'Heat'. But I don't even know what that actually means (and how to actually disable it). Thermostat like that doesn't have on/off only workload. It has different levels of opening valve to achieve different level of heating power. As far I understand, having scheduled setting enabled through the official app, with Away/Home set to some hours during the day, Eco2 sets heating power to be "just enough" to achieve its goal.

As far I see there's no indication of the mode the Eco2 is at the moment - I didn't see any difference in HA if there was Home or Away engaged.

Am missing something here? I know I'm very noobish with all of this :P

BTW I know you're responsible for wrapping up tools needed to add it to the hassio not the toole themselves, so this topic maybe shouldn't be meant for you, but I figured out I'll start with you as you should have knowledge about that and maybe the answer is quite simple ;)

**Comment by HBDK** [comment]
The eco2 thermostats are just "dumb" thermostats, you can tell them your desired temperature and they will try to maintain it using the build in temperature sensor, booth the official app and this add-on only provides ways of controlling that desired temperature.  And the heat state you see in home assistant probably doesn't mean or do anything.  
  
The only way to get the thermostat to open up and let heat into the radiator is to set the desired temp above the actual temp, you could definitely use home assistant to control the heat like that but unless you have a very solid background in control system (given your question I think it's safe to assume you don't) i wouldn't expect that to result in anything but wild temperature swings, short battery life and a large heating bill.  
  
I know I probably isn't the answer you wanted but i think you need to move your pc or get some fancier thermostats.

**Comment by Draghmar** [comment]
Nope, it isn't what I wanted to get but then again your answer is logical. Actually I didn't think how exactly I could achieve the thing I want. I just assumed everything will magically connect and that's it. ;) The main thing I didn't calculate was the fact that Eco2 has to somehow monitor surroundings in order to 'know' how much and for how long it should open valve. I assumed I would be able to feed Eco2 with data somehow...

If the 'Heat' doesn't do anything then why it's there?

Unfortunately there's no easy way to move my PC. The only thing I've manage to think of, was to put it on the balcony (it's right next to where I sit) but that would require a lot of work (like hole in the wall for example) and special case with humidity control - I've already made some plans about that because of the noise PC generates . ;)

Anyway, thanks for your response.
