### ISSUE TITLE
[Question] is scheduling possible and to what extend?

### ISSUE THREAD

**Issue by neuronflow** [HBDK/Eco2-Tools#9]
Hi,

the original Danfoss App, has scheduling implemented in a very limiting way. Only two temperatures, only 3 heating time slots.

Can I achieve more complex schedules like the following with this software? Will manual control still be useable and open window detection still work?

I need schedules like:
USER A home:
7:45-10:30 -> 24°C
10:30-12:00 -> 21°C
12-19:30 -> 23°C
19:30-0:00 -> 22°C
0:00-7:45 -> 16°C
etc.

USER B home:
7:45-10:30 -> 22°C
10:30-12:00 -> 19°C
12-19:30 -> 21°C
etc.

Background I have a baby and wife with very different heating requirements.

**Comment by HBDK** [comment]
I don't maintain the software i just package it, so this question is not really relevant here.

If you need help creating home assistant automations then please go look at the official documentation and address questions about automations to the HA forums.
